import type { AiProfile } from "../../src/shared/types";

export type CastProfile = AiProfile & {
  name: string;
};

export const AI_CAST: CastProfile[] = [
  {
    name: "Mara Voss",
    archetype: "The Operator",
    biography: "A former campaign field director who trusts vote counts more than vibes.",
    speechStyle: "Calm, clipped, and practical.",
    strategicStyle: "Builds quiet majority alliances and cuts threats early.",
    riskTolerance: "medium",
    loyalty: 46,
    deception: 74,
    threatSensitivity: 82,
    memorySummary: "Mara is watching for who controls information and who can be used as a number.",
  },
  {
    name: "Theo Grant",
    archetype: "The Loyalist",
    biography: "A firefighter who sees loyalty as both an ethic and a shield.",
    speechStyle: "Plainspoken, earnest, and direct.",
    strategicStyle: "Values trust, but turns if betrayed.",
    riskTolerance: "low",
    loyalty: 86,
    deception: 31,
    threatSensitivity: 57,
    memorySummary: "Theo wants a stable alliance and reacts strongly to broken promises.",
  },
  {
    name: "Lina Park",
    archetype: "The Analyst",
    biography: "A data scientist who maps every conversation into probabilities.",
    speechStyle: "Precise, skeptical, and measured.",
    strategicStyle: "Tracks vote math and exposes contradictions.",
    riskTolerance: "medium",
    loyalty: 58,
    deception: 55,
    threatSensitivity: 78,
    memorySummary: "Lina is comparing stated plans against plausible vote incentives.",
  },
  {
    name: "Darius Cole",
    archetype: "The Charmer",
    biography: "A bartender with a gift for making strangers feel chosen.",
    speechStyle: "Warm, funny, and disarming.",
    strategicStyle: "Uses warmth, humor, and flattery to gather information.",
    riskTolerance: "medium",
    loyalty: 62,
    deception: 69,
    threatSensitivity: 64,
    memorySummary: "Darius wants people to underestimate how much information he collects.",
  },
  {
    name: "Priya Nair",
    archetype: "The Assassin",
    biography: "A litigation consultant who smiles while finding leverage.",
    speechStyle: "Polite, cool, and quietly cutting.",
    strategicStyle: "Plays politely while engineering blindsides.",
    riskTolerance: "high",
    loyalty: 38,
    deception: 88,
    threatSensitivity: 84,
    memorySummary: "Priya is comfortable making promises she may need to break.",
  },
  {
    name: "Benji Stone",
    archetype: "The Free Agent",
    biography: "A freelance photographer who avoids being pinned down.",
    speechStyle: "Loose, casual, and evasive.",
    strategicStyle: "Avoids firm commitments and floats between groups.",
    riskTolerance: "high",
    loyalty: 35,
    deception: 66,
    threatSensitivity: 61,
    memorySummary: "Benji wants options and dislikes plans that make him accountable.",
  },
  {
    name: "Celeste Moreno",
    archetype: "The Social Anchor",
    biography: "A school principal who builds trust through attention and care.",
    speechStyle: "Grounded, empathetic, and observant.",
    strategicStyle: "Builds emotional bonds and protects close allies.",
    riskTolerance: "low",
    loyalty: 82,
    deception: 41,
    threatSensitivity: 60,
    memorySummary: "Celeste notices who feels isolated and uses that to build durable bonds.",
  },
  {
    name: "Knox Reed",
    archetype: "The Chaos Player",
    biography: "A poker dealer who knows panic can be profitable.",
    speechStyle: "Dry, provocative, and slippery.",
    strategicStyle: "Creates uncertainty to prevent stable majorities.",
    riskTolerance: "high",
    loyalty: 28,
    deception: 82,
    threatSensitivity: 73,
    memorySummary: "Knox prefers fractured groups and opportunistic votes.",
  },
];

export const selectCast = (count: number) => AI_CAST.slice(0, Math.max(2, Math.min(count, AI_CAST.length)));
